### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by nikosv** [ksungcaya/phpass#1]
Hello there.

I was wondering... does it work with Laravel 5?

**Comment by ksungcaya** [comment]
Hello

Unfortunately, It doesn't at the moment but I will do the Laravel 5 implementation this weekend.

Sorry about that. :)

**Comment by ksungcaya** [comment]
36ad273

**Comment by ksungcaya** [comment]
https://github.com/ksungcaya/phpass/commit/769737e1a7a5d255f5981b02996c6c13636ad273

**Comment by ksungcaya** [comment]
okay sorry if you received weird notifications. haha

Laravel 5 is now supported. https://github.com/ksungcaya/phpass/commit/769737e1a7a5d255f5981b02996c6c13636ad273

**Comment by nikosv** [comment]
thanks for your efforts. I am going to use it soon ;-)

**Comment by ksungcaya** [comment]
No worries.. Let me know if you experience any problem. Thanks!
