### ISSUE TITLE
Class '\[]' not found

### ISSUE THREAD

**Issue by jossemarGT** [ksungcaya/phpass#4]
Greetings!

I was wondering if someone can help me with this, I just added `phpass` package to my project, the `Ksungcaya\Phpass\PhpassServiceProvider` to my confi/app.php and changed the Auth driver to `phpass` in config/auth.php, but, when I try to do

``` php
Auth::attempt([
    'user_email' => Input::json()->get('email'),
    'user_pass' => Input::json()->get('password')]
);
```

The application responds with a 500 error with  `FatalErrorException in PhpassUserProvider.php line 126: Class '\[]' not found` message, it looks like I'm not initializing something because that line tries to instantiate the user model,  but I couldn't find out where do I have to pass the model's name...

Any hints?

**Comment by ksungcaya** [comment]
Hello,

What version of laravel are you using? 
Also, did you move your user model to a different folder? 

If so, you need to change your model path according to your user model's namespace in `config/auth.php`

**Comment by jossemarGT** [comment]
Hi! 
Thanks for your response. I forgot to mention that I'm using Laravel 5, the user model is in `app` directory and in `config/auth` I have `'driver' => 'phpass'` alonside `'model' => 'App\User'` which corresponds to the User model namespace.

I still don't have any clue, but if I'll update this thread if I find out something else.

**Comment by ksungcaya** [comment]
Please also note that currently it is only compatible with laravel 5.0.*

If you are using laravel 5.1 you might encounter a problem. I am currently having internet issues at home and I can not update this from my work place, so the update might take awhile. 

Sorry for the trouble.

**Comment by estankovic** [comment]
Hi, when we could expect an update ?

**Comment by ksungcaya** [comment]
Hello

Apologies for the very late reply.

I have created a new implementation of PHPass as the new Laravel made many changes since then.
You can find the instructions here, https://github.com/ksungcaya/phpass-laravel.

If you find any issues about the new implementation, just create a new issue on that repo. Thanks!
